[phases.setup]
nixPkgs = ['nodejs', 'chromium', 'glib', 'nss', 'fontconfig']

[phases.build]
cmds = ['npm install']

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = 'true'
//No Nixpacks, o caminho costuma ser este:
PUPPETEER_EXECUTABLE_PATH = '/usr/bin/google-chrome-stable'